//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Consuming_Web_Services.HealthWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HealthServiceSoap", Namespace="http://tempuri.org/")]
    public partial class HealthService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalculateBMIOperationCompleted;
        
        private System.Threading.SendOrPostCallback CaloriesBurnerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HealthService() {
            this.Url = global::Consuming_Web_Services.Properties.Settings.Default.Consuming_Web_Services_HealthWebService_HealthService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalculateBMICompletedEventHandler CalculateBMICompleted;
        
        /// <remarks/>
        public event CaloriesBurnerCompletedEventHandler CaloriesBurnerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateBMI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateBMI(double weight, double height) {
            object[] results = this.Invoke("CalculateBMI", new object[] {
                        weight,
                        height});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateBMIAsync(double weight, double height) {
            this.CalculateBMIAsync(weight, height, null);
        }
        
        /// <remarks/>
        public void CalculateBMIAsync(double weight, double height, object userState) {
            if ((this.CalculateBMIOperationCompleted == null)) {
                this.CalculateBMIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateBMIOperationCompleted);
            }
            this.InvokeAsync("CalculateBMI", new object[] {
                        weight,
                        height}, this.CalculateBMIOperationCompleted, userState);
        }
        
        private void OnCalculateBMIOperationCompleted(object arg) {
            if ((this.CalculateBMICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateBMICompleted(this, new CalculateBMICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CaloriesBurner", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CaloriesBurner(string gender, double weight, double height, int age) {
            object[] results = this.Invoke("CaloriesBurner", new object[] {
                        gender,
                        weight,
                        height,
                        age});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CaloriesBurnerAsync(string gender, double weight, double height, int age) {
            this.CaloriesBurnerAsync(gender, weight, height, age, null);
        }
        
        /// <remarks/>
        public void CaloriesBurnerAsync(string gender, double weight, double height, int age, object userState) {
            if ((this.CaloriesBurnerOperationCompleted == null)) {
                this.CaloriesBurnerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCaloriesBurnerOperationCompleted);
            }
            this.InvokeAsync("CaloriesBurner", new object[] {
                        gender,
                        weight,
                        height,
                        age}, this.CaloriesBurnerOperationCompleted, userState);
        }
        
        private void OnCaloriesBurnerOperationCompleted(object arg) {
            if ((this.CaloriesBurnerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CaloriesBurnerCompleted(this, new CaloriesBurnerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CalculateBMICompletedEventHandler(object sender, CalculateBMICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateBMICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateBMICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CaloriesBurnerCompletedEventHandler(object sender, CaloriesBurnerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaloriesBurnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CaloriesBurnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591