//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consuming_Web_Services.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.AddtoCartSoap")]
    public interface AddtoCartSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddItem", ReplyAction="*")]
        Consuming_Web_Services.ServiceReference1.AddItemResponse AddItem(Consuming_Web_Services.ServiceReference1.AddItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddItem", ReplyAction="*")]
        System.Threading.Tasks.Task<Consuming_Web_Services.ServiceReference1.AddItemResponse> AddItemAsync(Consuming_Web_Services.ServiceReference1.AddItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddItem", Namespace="http://tempuri.org/", Order=0)]
        public Consuming_Web_Services.ServiceReference1.AddItemRequestBody Body;
        
        public AddItemRequest() {
        }
        
        public AddItemRequest(Consuming_Web_Services.ServiceReference1.AddItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public AddItemRequestBody() {
        }
        
        public AddItemRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consuming_Web_Services.ServiceReference1.AddItemResponseBody Body;
        
        public AddItemResponse() {
        }
        
        public AddItemResponse(Consuming_Web_Services.ServiceReference1.AddItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddItemResponseBody {
        
        public AddItemResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddtoCartSoapChannel : Consuming_Web_Services.ServiceReference1.AddtoCartSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddtoCartSoapClient : System.ServiceModel.ClientBase<Consuming_Web_Services.ServiceReference1.AddtoCartSoap>, Consuming_Web_Services.ServiceReference1.AddtoCartSoap {
        
        public AddtoCartSoapClient() {
        }
        
        public AddtoCartSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddtoCartSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddtoCartSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddtoCartSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consuming_Web_Services.ServiceReference1.AddItemResponse Consuming_Web_Services.ServiceReference1.AddtoCartSoap.AddItem(Consuming_Web_Services.ServiceReference1.AddItemRequest request) {
            return base.Channel.AddItem(request);
        }
        
        public void AddItem(string name) {
            Consuming_Web_Services.ServiceReference1.AddItemRequest inValue = new Consuming_Web_Services.ServiceReference1.AddItemRequest();
            inValue.Body = new Consuming_Web_Services.ServiceReference1.AddItemRequestBody();
            inValue.Body.name = name;
            Consuming_Web_Services.ServiceReference1.AddItemResponse retVal = ((Consuming_Web_Services.ServiceReference1.AddtoCartSoap)(this)).AddItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consuming_Web_Services.ServiceReference1.AddItemResponse> Consuming_Web_Services.ServiceReference1.AddtoCartSoap.AddItemAsync(Consuming_Web_Services.ServiceReference1.AddItemRequest request) {
            return base.Channel.AddItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consuming_Web_Services.ServiceReference1.AddItemResponse> AddItemAsync(string name) {
            Consuming_Web_Services.ServiceReference1.AddItemRequest inValue = new Consuming_Web_Services.ServiceReference1.AddItemRequest();
            inValue.Body = new Consuming_Web_Services.ServiceReference1.AddItemRequestBody();
            inValue.Body.name = name;
            return ((Consuming_Web_Services.ServiceReference1.AddtoCartSoap)(this)).AddItemAsync(inValue);
        }
    }
}
