// <auto-generated />
using System;
using BankingMicroService.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankingMicroService.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20230614212516_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankingMicroService.Models.Bank_Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber");

                    b.Property<double>("Amount");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<string>("TransactionType");

                    b.HasKey("TransactionId");

                    b.ToTable("Bank_Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNumber = "123456789",
                            Amount = 100.0,
                            TransactionDate = new DateTime(2023, 6, 15, 2, 25, 16, 721, DateTimeKind.Local).AddTicks(4327),
                            TransactionType = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNumber = "987654321",
                            Amount = 50.0,
                            TransactionDate = new DateTime(2023, 6, 15, 2, 25, 16, 722, DateTimeKind.Local).AddTicks(2959),
                            TransactionType = "Withdrawal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
